// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpcinter option

package rpcinter

import (
	"time"
	"github.com/jsn4ke/chat/pkg/pb/message_rpc"
)

type RpcAuthCli interface {
	RpcAuthCheckAsk(in *message_rpc.RpcAuthCheckAsk, cancel <-chan struct{}, timeout time.Duration) error
}
