// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpcinter option

package rpcinter

import (
	"time"
	"github.com/jsn4ke/chat/pkg/pb/message_rpc"
)

type RpcLogicCli interface {
	RpcLogicSigninRequest(in *message_rpc.RpcLogicSigninRequest, cancel <-chan struct{}, timeout time.Duration) (*message_rpc.RpcLogicSigninResponse, error)
	RpcLogicSubscribeOrUnsubscribAsk(in *message_rpc.RpcLogicSubscribeOrUnsubscribAsk, cancel <-chan struct{}, timeout time.Duration) error
	RpcLogicReSubscribeAsk(in *message_rpc.RpcLogicReSubscribeAsk, cancel <-chan struct{}, timeout time.Duration) error
}
type RpcLogicSvr interface {
	Run()
	RpcLogicSigninRequest(in *message_rpc.RpcLogicSigninRequest) (*message_rpc.RpcLogicSigninResponse, error)
	RpcLogicSubscribeOrUnsubscribAsk(in *message_rpc.RpcLogicSubscribeOrUnsubscribAsk) error
	RpcLogicReSubscribeAsk(in *message_rpc.RpcLogicReSubscribeAsk) error
}
