// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpcext option
package message_rpc

import (
	jsn_rpc "github.com/jsn4ke/jsn_net/rpc"
	"google.golang.org/protobuf/proto"
)

var (
	_ jsn_rpc.RpcUnit = (*RpcLogicSigninRequest)(nil)
	_ jsn_rpc.RpcUnit = (*RpcLogicSigninResponse)(nil)
	_ jsn_rpc.RpcUnit = (*RpcLogicSubscribeOrUnsubscribAsk)(nil)
	_ jsn_rpc.RpcUnit = (*RpcLogicReSubscribeAsk)(nil)
	_ jsn_rpc.RpcUnit = (*RpcLogicChat2GuildAsk)(nil)
	_ jsn_rpc.RpcUnit = (*RpcLogicChat2WorldAsk)(nil)
	_ jsn_rpc.RpcUnit = (*RpcLogicChat2DirectAsk)(nil)
)

func (*RpcLogicSigninRequest) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcLogicSigninRequest)
}
func (x *RpcLogicSigninRequest) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcLogicSigninRequest) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcLogicSigninRequest) New() jsn_rpc.RpcUnit {
	return new(RpcLogicSigninRequest)
}
func (*RpcLogicSigninResponse) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcLogicSigninResponse)
}
func (x *RpcLogicSigninResponse) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcLogicSigninResponse) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcLogicSigninResponse) New() jsn_rpc.RpcUnit {
	return new(RpcLogicSigninResponse)
}
func (*RpcLogicSubscribeOrUnsubscribAsk) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcLogicSubscribeOrUnsubscribAsk)
}
func (x *RpcLogicSubscribeOrUnsubscribAsk) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcLogicSubscribeOrUnsubscribAsk) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcLogicSubscribeOrUnsubscribAsk) New() jsn_rpc.RpcUnit {
	return new(RpcLogicSubscribeOrUnsubscribAsk)
}
func (*RpcLogicReSubscribeAsk) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcLogicReSubscribeAsk)
}
func (x *RpcLogicReSubscribeAsk) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcLogicReSubscribeAsk) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcLogicReSubscribeAsk) New() jsn_rpc.RpcUnit {
	return new(RpcLogicReSubscribeAsk)
}
func (*RpcLogicChat2GuildAsk) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcLogicChat2GuildAsk)
}
func (x *RpcLogicChat2GuildAsk) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcLogicChat2GuildAsk) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcLogicChat2GuildAsk) New() jsn_rpc.RpcUnit {
	return new(RpcLogicChat2GuildAsk)
}
func (*RpcLogicChat2WorldAsk) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcLogicChat2WorldAsk)
}
func (x *RpcLogicChat2WorldAsk) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcLogicChat2WorldAsk) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcLogicChat2WorldAsk) New() jsn_rpc.RpcUnit {
	return new(RpcLogicChat2WorldAsk)
}
func (*RpcLogicChat2DirectAsk) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcLogicChat2DirectAsk)
}
func (x *RpcLogicChat2DirectAsk) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcLogicChat2DirectAsk) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcLogicChat2DirectAsk) New() jsn_rpc.RpcUnit {
	return new(RpcLogicChat2DirectAsk)
}
