// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpcext option
package message_rpc

import (
	jsn_rpc "github.com/jsn4ke/jsn_net/rpc"
	"google.golang.org/protobuf/proto"
)

var (
	_ jsn_rpc.RpcUnit = (*RpcPusherChat2GuildSync)(nil)
	_ jsn_rpc.RpcUnit = (*RpcPusherChat2WorldSync)(nil)
	_ jsn_rpc.RpcUnit = (*RpcPusherChat2DirectSync)(nil)
)

func (*RpcPusherChat2GuildSync) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcPusherChat2GuildSync)
}
func (x *RpcPusherChat2GuildSync) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcPusherChat2GuildSync) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcPusherChat2GuildSync) New() jsn_rpc.RpcUnit {
	return new(RpcPusherChat2GuildSync)
}
func (*RpcPusherChat2WorldSync) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcPusherChat2WorldSync)
}
func (x *RpcPusherChat2WorldSync) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcPusherChat2WorldSync) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcPusherChat2WorldSync) New() jsn_rpc.RpcUnit {
	return new(RpcPusherChat2WorldSync)
}
func (*RpcPusherChat2DirectSync) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcPusherChat2DirectSync)
}
func (x *RpcPusherChat2DirectSync) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcPusherChat2DirectSync) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcPusherChat2DirectSync) New() jsn_rpc.RpcUnit {
	return new(RpcPusherChat2DirectSync)
}
