// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpcext option
package message_rpc

import (
	jsn_rpc "github.com/jsn4ke/jsn_net/rpc"
	"google.golang.org/protobuf/proto"
)

var (
	_ jsn_rpc.RpcUnit = (*RpcAuthCheckAsk)(nil)
)

func (*RpcAuthCheckAsk) CmdId() uint32 {
	return uint32(RpcCmd_RpcCmd_RpcAuthCheckAsk)
}
func (x *RpcAuthCheckAsk) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RpcAuthCheckAsk) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RpcAuthCheckAsk) New() jsn_rpc.RpcUnit {
	return new(RpcAuthCheckAsk)
}
