// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: rpc/cmd.proto

package message_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcCmd int32

const (
	RpcCmd_RpcCmd_None                             RpcCmd = 0
	RpcCmd_RpcCmd_RpcAuthCheckAsk                  RpcCmd = 10001
	RpcCmd_RpcCmd_RpcLogicSigninRequest            RpcCmd = 20001
	RpcCmd_RpcCmd_RpcLogicSigninResponse           RpcCmd = 20002
	RpcCmd_RpcCmd_RpcLogicSubscribeOrUnsubscribAsk RpcCmd = 20003
	RpcCmd_RpcCmd_RpcLogicReSubscribeAsk           RpcCmd = 20004
)

// Enum value maps for RpcCmd.
var (
	RpcCmd_name = map[int32]string{
		0:     "RpcCmd_None",
		10001: "RpcCmd_RpcAuthCheckAsk",
		20001: "RpcCmd_RpcLogicSigninRequest",
		20002: "RpcCmd_RpcLogicSigninResponse",
		20003: "RpcCmd_RpcLogicSubscribeOrUnsubscribAsk",
		20004: "RpcCmd_RpcLogicReSubscribeAsk",
	}
	RpcCmd_value = map[string]int32{
		"RpcCmd_None":                             0,
		"RpcCmd_RpcAuthCheckAsk":                  10001,
		"RpcCmd_RpcLogicSigninRequest":            20001,
		"RpcCmd_RpcLogicSigninResponse":           20002,
		"RpcCmd_RpcLogicSubscribeOrUnsubscribAsk": 20003,
		"RpcCmd_RpcLogicReSubscribeAsk":           20004,
	}
)

func (x RpcCmd) Enum() *RpcCmd {
	p := new(RpcCmd)
	*p = x
	return p
}

func (x RpcCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_cmd_proto_enumTypes[0].Descriptor()
}

func (RpcCmd) Type() protoreflect.EnumType {
	return &file_rpc_cmd_proto_enumTypes[0]
}

func (x RpcCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcCmd.Descriptor instead.
func (RpcCmd) EnumDescriptor() ([]byte, []int) {
	return file_rpc_cmd_proto_rawDescGZIP(), []int{0}
}

var File_rpc_cmd_proto protoreflect.FileDescriptor

var file_rpc_cmd_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2a, 0xd3, 0x01, 0x0a,
	0x06, 0x52, 0x70, 0x63, 0x43, 0x6d, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x70, 0x63, 0x43, 0x6d,
	0x64, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x16, 0x52, 0x70, 0x63, 0x43,
	0x6d, 0x64, 0x5f, 0x52, 0x70, 0x63, 0x41, 0x75, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41,
	0x73, 0x6b, 0x10, 0x91, 0x4e, 0x12, 0x22, 0x0a, 0x1c, 0x52, 0x70, 0x63, 0x43, 0x6d, 0x64, 0x5f,
	0x52, 0x70, 0x63, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0xa1, 0x9c, 0x01, 0x12, 0x23, 0x0a, 0x1d, 0x52, 0x70, 0x63,
	0x43, 0x6d, 0x64, 0x5f, 0x52, 0x70, 0x63, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x53, 0x69, 0x67, 0x6e,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0xa2, 0x9c, 0x01, 0x12, 0x2d,
	0x0a, 0x27, 0x52, 0x70, 0x63, 0x43, 0x6d, 0x64, 0x5f, 0x52, 0x70, 0x63, 0x4c, 0x6f, 0x67, 0x69,
	0x63, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x72, 0x55, 0x6e, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x41, 0x73, 0x6b, 0x10, 0xa3, 0x9c, 0x01, 0x12, 0x23, 0x0a,
	0x1d, 0x52, 0x70, 0x63, 0x43, 0x6d, 0x64, 0x5f, 0x52, 0x70, 0x63, 0x4c, 0x6f, 0x67, 0x69, 0x63,
	0x52, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x73, 0x6b, 0x10, 0xa4,
	0x9c, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_cmd_proto_rawDescOnce sync.Once
	file_rpc_cmd_proto_rawDescData = file_rpc_cmd_proto_rawDesc
)

func file_rpc_cmd_proto_rawDescGZIP() []byte {
	file_rpc_cmd_proto_rawDescOnce.Do(func() {
		file_rpc_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_cmd_proto_rawDescData)
	})
	return file_rpc_cmd_proto_rawDescData
}

var file_rpc_cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_cmd_proto_goTypes = []interface{}{
	(RpcCmd)(0), // 0: message_rpc.RpcCmd
}
var file_rpc_cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_cmd_proto_init() }
func file_rpc_cmd_proto_init() {
	if File_rpc_cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_cmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_cmd_proto_goTypes,
		DependencyIndexes: file_rpc_cmd_proto_depIdxs,
		EnumInfos:         file_rpc_cmd_proto_enumTypes,
	}.Build()
	File_rpc_cmd_proto = out.File
	file_rpc_cmd_proto_rawDesc = nil
	file_rpc_cmd_proto_goTypes = nil
	file_rpc_cmd_proto_depIdxs = nil
}
