// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: message_rpc/gateway.proto

package message_rpc

import (
	message_obj "github.com/jsn4ke/chat/pkg/pb/message_obj"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcGatewayUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RpcGatewayUnit) Reset() {
	*x = RpcGatewayUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcGatewayUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGatewayUnit) ProtoMessage() {}

func (x *RpcGatewayUnit) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGatewayUnit.ProtoReflect.Descriptor instead.
func (*RpcGatewayUnit) Descriptor() ([]byte, []int) {
	return file_message_rpc_gateway_proto_rawDescGZIP(), []int{0}
}

type RpcGatewayKickUserSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      uint64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ClientId *ClientId `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *RpcGatewayKickUserSync) Reset() {
	*x = RpcGatewayKickUserSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcGatewayKickUserSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGatewayKickUserSync) ProtoMessage() {}

func (x *RpcGatewayKickUserSync) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGatewayKickUserSync.ProtoReflect.Descriptor instead.
func (*RpcGatewayKickUserSync) Descriptor() ([]byte, []int) {
	return file_message_rpc_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RpcGatewayKickUserSync) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RpcGatewayKickUserSync) GetClientId() *ClientId {
	if x != nil {
		return x.ClientId
	}
	return nil
}

type RpcGatewayInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RpcGatewayInfoRequest) Reset() {
	*x = RpcGatewayInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcGatewayInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGatewayInfoRequest) ProtoMessage() {}

func (x *RpcGatewayInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGatewayInfoRequest.ProtoReflect.Descriptor instead.
func (*RpcGatewayInfoRequest) Descriptor() ([]byte, []int) {
	return file_message_rpc_gateway_proto_rawDescGZIP(), []int{2}
}

type RpcGatewayInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayId uint32 `protobuf:"varint,1,opt,name=gatewayId,proto3" json:"gatewayId,omitempty"`
}

func (x *RpcGatewayInfoResponse) Reset() {
	*x = RpcGatewayInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcGatewayInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGatewayInfoResponse) ProtoMessage() {}

func (x *RpcGatewayInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGatewayInfoResponse.ProtoReflect.Descriptor instead.
func (*RpcGatewayInfoResponse) Descriptor() ([]byte, []int) {
	return file_message_rpc_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RpcGatewayInfoResponse) GetGatewayId() uint32 {
	if x != nil {
		return x.GatewayId
	}
	return 0
}

type RpcGatewayChannelPushSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cm []*message_obj.ChannelMessage `protobuf:"bytes,1,rep,name=cm,proto3" json:"cm,omitempty"`
}

func (x *RpcGatewayChannelPushSync) Reset() {
	*x = RpcGatewayChannelPushSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcGatewayChannelPushSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGatewayChannelPushSync) ProtoMessage() {}

func (x *RpcGatewayChannelPushSync) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGatewayChannelPushSync.ProtoReflect.Descriptor instead.
func (*RpcGatewayChannelPushSync) Descriptor() ([]byte, []int) {
	return file_message_rpc_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RpcGatewayChannelPushSync) GetCm() []*message_obj.ChannelMessage {
	if x != nil {
		return x.Cm
	}
	return nil
}

type RpcUnionGatewayUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RpcUnionGatewayUnit) Reset() {
	*x = RpcUnionGatewayUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcUnionGatewayUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcUnionGatewayUnit) ProtoMessage() {}

func (x *RpcUnionGatewayUnit) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcUnionGatewayUnit.ProtoReflect.Descriptor instead.
func (*RpcUnionGatewayUnit) Descriptor() ([]byte, []int) {
	return file_message_rpc_gateway_proto_rawDescGZIP(), []int{5}
}

type RpcUnionGatewayUploadGatewayInfoAsk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewaId uint32 `protobuf:"varint,1,opt,name=gatewaId,proto3" json:"gatewaId,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RpcUnionGatewayUploadGatewayInfoAsk) Reset() {
	*x = RpcUnionGatewayUploadGatewayInfoAsk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcUnionGatewayUploadGatewayInfoAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcUnionGatewayUploadGatewayInfoAsk) ProtoMessage() {}

func (x *RpcUnionGatewayUploadGatewayInfoAsk) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcUnionGatewayUploadGatewayInfoAsk.ProtoReflect.Descriptor instead.
func (*RpcUnionGatewayUploadGatewayInfoAsk) Descriptor() ([]byte, []int) {
	return file_message_rpc_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *RpcUnionGatewayUploadGatewayInfoAsk) GetGatewaId() uint32 {
	if x != nil {
		return x.GatewaId
	}
	return 0
}

func (x *RpcUnionGatewayUploadGatewayInfoAsk) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_message_rpc_gateway_proto protoreflect.FileDescriptor

var file_message_rpc_gateway_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x1a, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e,
	0x52, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x5d,
	0x0a, 0x16, 0x52, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x17, 0x0a,
	0x15, 0x52, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x16, 0x52, 0x70, 0x63, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x22, 0x48,
	0x0a, 0x19, 0x52, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x50, 0x75, 0x73, 0x68, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x2b, 0x0a, 0x02, 0x63,
	0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x02, 0x63, 0x6d, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x70, 0x63, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x22,
	0x5b, 0x0a, 0x23, 0x52, 0x70, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x41, 0x73, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x73, 0x6e, 0x34, 0x6b,
	0x65, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_message_rpc_gateway_proto_rawDescOnce sync.Once
	file_message_rpc_gateway_proto_rawDescData = file_message_rpc_gateway_proto_rawDesc
)

func file_message_rpc_gateway_proto_rawDescGZIP() []byte {
	file_message_rpc_gateway_proto_rawDescOnce.Do(func() {
		file_message_rpc_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_rpc_gateway_proto_rawDescData)
	})
	return file_message_rpc_gateway_proto_rawDescData
}

var file_message_rpc_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_rpc_gateway_proto_goTypes = []interface{}{
	(*RpcGatewayUnit)(nil),                      // 0: message_rpc.RpcGatewayUnit
	(*RpcGatewayKickUserSync)(nil),              // 1: message_rpc.RpcGatewayKickUserSync
	(*RpcGatewayInfoRequest)(nil),               // 2: message_rpc.RpcGatewayInfoRequest
	(*RpcGatewayInfoResponse)(nil),              // 3: message_rpc.RpcGatewayInfoResponse
	(*RpcGatewayChannelPushSync)(nil),           // 4: message_rpc.RpcGatewayChannelPushSync
	(*RpcUnionGatewayUnit)(nil),                 // 5: message_rpc.RpcUnionGatewayUnit
	(*RpcUnionGatewayUploadGatewayInfoAsk)(nil), // 6: message_rpc.RpcUnionGatewayUploadGatewayInfoAsk
	(*ClientId)(nil),                            // 7: message_rpc.ClientId
	(*message_obj.ChannelMessage)(nil),          // 8: message_obj.ChannelMessage
}
var file_message_rpc_gateway_proto_depIdxs = []int32{
	7, // 0: message_rpc.RpcGatewayKickUserSync.clientId:type_name -> message_rpc.ClientId
	8, // 1: message_rpc.RpcGatewayChannelPushSync.cm:type_name -> message_obj.ChannelMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_rpc_gateway_proto_init() }
func file_message_rpc_gateway_proto_init() {
	if File_message_rpc_gateway_proto != nil {
		return
	}
	file_message_rpc_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_rpc_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcGatewayUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcGatewayKickUserSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcGatewayInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcGatewayInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcGatewayChannelPushSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcUnionGatewayUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcUnionGatewayUploadGatewayInfoAsk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_rpc_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_rpc_gateway_proto_goTypes,
		DependencyIndexes: file_message_rpc_gateway_proto_depIdxs,
		MessageInfos:      file_message_rpc_gateway_proto_msgTypes,
	}.Build()
	File_message_rpc_gateway_proto = out.File
	file_message_rpc_gateway_proto_rawDesc = nil
	file_message_rpc_gateway_proto_goTypes = nil
	file_message_rpc_gateway_proto_depIdxs = nil
}
