// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: message_rpc/pusher.proto

package message_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcPusherUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RpcPusherUnit) Reset() {
	*x = RpcPusherUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_pusher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcPusherUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPusherUnit) ProtoMessage() {}

func (x *RpcPusherUnit) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_pusher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPusherUnit.ProtoReflect.Descriptor instead.
func (*RpcPusherUnit) Descriptor() ([]byte, []int) {
	return file_message_rpc_pusher_proto_rawDescGZIP(), []int{0}
}

type RpcPusherChat2GuildSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuildId uint64 `protobuf:"varint,1,opt,name=guildId,proto3" json:"guildId,omitempty"`
	Body    []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RpcPusherChat2GuildSync) Reset() {
	*x = RpcPusherChat2GuildSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_pusher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcPusherChat2GuildSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPusherChat2GuildSync) ProtoMessage() {}

func (x *RpcPusherChat2GuildSync) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_pusher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPusherChat2GuildSync.ProtoReflect.Descriptor instead.
func (*RpcPusherChat2GuildSync) Descriptor() ([]byte, []int) {
	return file_message_rpc_pusher_proto_rawDescGZIP(), []int{1}
}

func (x *RpcPusherChat2GuildSync) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *RpcPusherChat2GuildSync) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RpcPusherChat2WorldSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldId uint64 `protobuf:"varint,1,opt,name=worldId,proto3" json:"worldId,omitempty"`
	Body    []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RpcPusherChat2WorldSync) Reset() {
	*x = RpcPusherChat2WorldSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_pusher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcPusherChat2WorldSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPusherChat2WorldSync) ProtoMessage() {}

func (x *RpcPusherChat2WorldSync) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_pusher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPusherChat2WorldSync.ProtoReflect.Descriptor instead.
func (*RpcPusherChat2WorldSync) Descriptor() ([]byte, []int) {
	return file_message_rpc_pusher_proto_rawDescGZIP(), []int{2}
}

func (x *RpcPusherChat2WorldSync) GetWorldId() uint64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *RpcPusherChat2WorldSync) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RpcPusherChat2DirectSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ReceiveId uint64 `protobuf:"varint,2,opt,name=receiveId,proto3" json:"receiveId,omitempty"`
	Body      []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RpcPusherChat2DirectSync) Reset() {
	*x = RpcPusherChat2DirectSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_rpc_pusher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcPusherChat2DirectSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPusherChat2DirectSync) ProtoMessage() {}

func (x *RpcPusherChat2DirectSync) ProtoReflect() protoreflect.Message {
	mi := &file_message_rpc_pusher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPusherChat2DirectSync.ProtoReflect.Descriptor instead.
func (*RpcPusherChat2DirectSync) Descriptor() ([]byte, []int) {
	return file_message_rpc_pusher_proto_rawDescGZIP(), []int{3}
}

func (x *RpcPusherChat2DirectSync) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RpcPusherChat2DirectSync) GetReceiveId() uint64 {
	if x != nil {
		return x.ReceiveId
	}
	return 0
}

func (x *RpcPusherChat2DirectSync) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_message_rpc_pusher_proto protoreflect.FileDescriptor

var file_message_rpc_pusher_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x75,
	0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x70, 0x63, 0x50, 0x75,
	0x73, 0x68, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x47, 0x0a, 0x17, 0x52, 0x70, 0x63, 0x50,
	0x75, 0x73, 0x68, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x32, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x53,
	0x79, 0x6e, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x47, 0x0a, 0x17, 0x52, 0x70, 0x63, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x43, 0x68,
	0x61, 0x74, 0x32, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x5e, 0x0a, 0x18, 0x52, 0x70,
	0x63, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x32, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x73, 0x6e, 0x34, 0x6b, 0x65, 0x2f,
	0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_rpc_pusher_proto_rawDescOnce sync.Once
	file_message_rpc_pusher_proto_rawDescData = file_message_rpc_pusher_proto_rawDesc
)

func file_message_rpc_pusher_proto_rawDescGZIP() []byte {
	file_message_rpc_pusher_proto_rawDescOnce.Do(func() {
		file_message_rpc_pusher_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_rpc_pusher_proto_rawDescData)
	})
	return file_message_rpc_pusher_proto_rawDescData
}

var file_message_rpc_pusher_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_rpc_pusher_proto_goTypes = []interface{}{
	(*RpcPusherUnit)(nil),            // 0: message_rpc.RpcPusherUnit
	(*RpcPusherChat2GuildSync)(nil),  // 1: message_rpc.RpcPusherChat2GuildSync
	(*RpcPusherChat2WorldSync)(nil),  // 2: message_rpc.RpcPusherChat2WorldSync
	(*RpcPusherChat2DirectSync)(nil), // 3: message_rpc.RpcPusherChat2DirectSync
}
var file_message_rpc_pusher_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_rpc_pusher_proto_init() }
func file_message_rpc_pusher_proto_init() {
	if File_message_rpc_pusher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_rpc_pusher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcPusherUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_pusher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcPusherChat2GuildSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_pusher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcPusherChat2WorldSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_rpc_pusher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcPusherChat2DirectSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_rpc_pusher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_rpc_pusher_proto_goTypes,
		DependencyIndexes: file_message_rpc_pusher_proto_depIdxs,
		MessageInfos:      file_message_rpc_pusher_proto_msgTypes,
	}.Build()
	File_message_rpc_pusher_proto = out.File
	file_message_rpc_pusher_proto_rawDesc = nil
	file_message_rpc_pusher_proto_goTypes = nil
	file_message_rpc_pusher_proto_depIdxs = nil
}
