// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpccli option

package api

import (
	"time"

	"github.com/jsn4ke/chat/pkg/inter/rpcinter"
	"github.com/jsn4ke/chat/pkg/pb/message_rpc"
	jsn_rpc "github.com/jsn4ke/jsn_net/rpc"
)

func NewRpcAuthCli(cli *jsn_rpc.Client) rpcinter.RpcAuthCli {
	c := new(rpcAuthCli)
	c.cli = cli
	return c
}

type (
	rpcAuthCli struct {
		cli *jsn_rpc.Client
	}
	EmptyRpcAuthCli struct{}
)

func (c *rpcAuthCli) RpcAuthCheckAsk(in *message_rpc.RpcAuthCheckAsk, cancel <-chan struct{}, timeout time.Duration) error {
	return c.cli.Ask(in, cancel, timeout)
}
func (c *EmptyRpcAuthCli) RpcAuthCheckAsk(in *message_rpc.RpcAuthCheckAsk, cancel <-chan struct{}, timeout time.Duration) error {
	return EmptyRpcCliError
}
