// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpcinter option

package rpcinter

import (
	"time"
	"github.com/jsn4ke/chat/pkg/pb/message_rpc"
	jsn_rpc "github.com/jsn4ke/jsn_net/rpc"
)

type RpcAuthCli interface {
	Cli() *jsn_rpc.Client
	RpcAuthCheckAsk(in *message_rpc.RpcAuthCheckAsk, cancel <-chan struct{}, timeout time.Duration) error
}
type RpcAuthSvrWrap interface {
	RpcAuthCheckAsk(in *message_rpc.RpcAuthCheckAsk) error
}
type RpcAuthSvr interface {
	Run()
	RpcAuthSvrWrap
}
