// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpcinter option

package rpcinter

import (
	"time"
	"github.com/jsn4ke/chat/pkg/pb/message_rpc"
	jsn_rpc "github.com/jsn4ke/jsn_net/rpc"
)

type RpcGatewayCli interface {
	Cli() *jsn_rpc.Client
	RpcGatewayKickUserSync(in *message_rpc.RpcGatewayKickUserSync)
	RpcGatewayInfoRequest(in *message_rpc.RpcGatewayInfoRequest, cancel <-chan struct{}, timeout time.Duration) (*message_rpc.RpcGatewayInfoResponse, error)
	RpcGatewayChannelPushSync(in *message_rpc.RpcGatewayChannelPushSync)
}
type RpcUnionGatewayCli interface {
	Cli() *jsn_rpc.Client
	RpcUnionGatewayUploadGatewayInfoAsk(in *message_rpc.RpcUnionGatewayUploadGatewayInfoAsk, cancel <-chan struct{}, timeout time.Duration) error
}
type RpcGatewaySvrWrap interface {
	RpcGatewayKickUserSync(in *message_rpc.RpcGatewayKickUserSync)
	RpcGatewayInfoRequest(in *message_rpc.RpcGatewayInfoRequest) (*message_rpc.RpcGatewayInfoResponse, error)
	RpcGatewayChannelPushSync(in *message_rpc.RpcGatewayChannelPushSync)
}
type RpcGatewaySvr interface {
	Run()
	RpcGatewaySvrWrap
}
type RpcUnionGatewaySvrWrap interface {
	RpcUnionGatewayUploadGatewayInfoAsk(in *message_rpc.RpcUnionGatewayUploadGatewayInfoAsk) error
}
type RpcUnionGatewaySvr interface {
	Run()
	RpcUnionGatewaySvrWrap
}
