// Code generated by protoc-gen-chat. DO NOT EDIT.
// rpcinter option

package rpcinter

import (
	"time"
	"github.com/jsn4ke/chat/pkg/pb/message_rpc"
	jsn_rpc "github.com/jsn4ke/jsn_net/rpc"
)

type RpcLogicCli interface {
	Cli() *jsn_rpc.Client
	RpcLogicSigninRequest(in *message_rpc.RpcLogicSigninRequest, cancel <-chan struct{}, timeout time.Duration) (*message_rpc.RpcLogicSigninResponse, error)
	RpcLogicSubscribeOrUnsubscribAsk(in *message_rpc.RpcLogicSubscribeOrUnsubscribAsk, cancel <-chan struct{}, timeout time.Duration) error
	RpcLogicReSubscribeAsk(in *message_rpc.RpcLogicReSubscribeAsk, cancel <-chan struct{}, timeout time.Duration) error
	RpcLogicChat2GuildAsk(in *message_rpc.RpcLogicChat2GuildAsk, cancel <-chan struct{}, timeout time.Duration) error
	RpcLogicChat2WorldAsk(in *message_rpc.RpcLogicChat2WorldAsk, cancel <-chan struct{}, timeout time.Duration) error
	RpcLogicChat2DirectAsk(in *message_rpc.RpcLogicChat2DirectAsk, cancel <-chan struct{}, timeout time.Duration) error
}
type RpcLogicSvrWrap interface {
	RpcLogicSigninRequest(in *message_rpc.RpcLogicSigninRequest) (*message_rpc.RpcLogicSigninResponse, error)
	RpcLogicSubscribeOrUnsubscribAsk(in *message_rpc.RpcLogicSubscribeOrUnsubscribAsk) error
	RpcLogicReSubscribeAsk(in *message_rpc.RpcLogicReSubscribeAsk) error
	RpcLogicChat2GuildAsk(in *message_rpc.RpcLogicChat2GuildAsk) error
	RpcLogicChat2WorldAsk(in *message_rpc.RpcLogicChat2WorldAsk) error
	RpcLogicChat2DirectAsk(in *message_rpc.RpcLogicChat2DirectAsk) error
}
type RpcLogicSvr interface {
	Run()
	RpcLogicSvrWrap
}
