// Code generated by protoc-gen-chat. DO NOT EDIT.
// cli option
package message_cli

import (
	"google.golang.org/protobuf/proto"
)

func init() {
	AllMessage[uint32(CliCmd_CliCmd_ResponseCliSucces)] = new(ResponseCliSucces)
	AllMessage[uint32(CliCmd_CliCmd_ResponseCliFailure)] = new(ResponseCliFailure)
	AllMessage[uint32(CliCmd_CliCmd_RequestSignIn)] = new(RequestSignIn)
	AllMessage[uint32(CliCmd_CliCmd_RequestChat2Guild)] = new(RequestChat2Guild)
	AllMessage[uint32(CliCmd_CliCmd_RequestChat2World)] = new(RequestChat2World)
	AllMessage[uint32(CliCmd_CliCmd_RequestChat2Direct)] = new(RequestChat2Direct)
	AllMessage[uint32(CliCmd_CliCmd_ResponseChatInfo)] = new(ResponseChatInfo)
	InComingMessage[uint32(CliCmd_CliCmd_RequestSignIn)] = new(RequestSignIn)
	InComingMessage[uint32(CliCmd_CliCmd_RequestChat2Guild)] = new(RequestChat2Guild)
	InComingMessage[uint32(CliCmd_CliCmd_RequestChat2World)] = new(RequestChat2World)
	InComingMessage[uint32(CliCmd_CliCmd_RequestChat2Direct)] = new(RequestChat2Direct)
}
func (*ResponseCliSucces) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_ResponseCliSucces)
}
func (x *ResponseCliSucces) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *ResponseCliSucces) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*ResponseCliSucces) New() CliMessage {
	return new(ResponseCliSucces)
}
func (*ResponseCliFailure) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_ResponseCliFailure)
}
func (x *ResponseCliFailure) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *ResponseCliFailure) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*ResponseCliFailure) New() CliMessage {
	return new(ResponseCliFailure)
}
func (*RequestSignIn) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_RequestSignIn)
}
func (x *RequestSignIn) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RequestSignIn) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RequestSignIn) New() CliMessage {
	return new(RequestSignIn)
}
func (*RequestChat2Guild) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_RequestChat2Guild)
}
func (x *RequestChat2Guild) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RequestChat2Guild) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RequestChat2Guild) New() CliMessage {
	return new(RequestChat2Guild)
}
func (*RequestChat2World) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_RequestChat2World)
}
func (x *RequestChat2World) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RequestChat2World) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RequestChat2World) New() CliMessage {
	return new(RequestChat2World)
}
func (*RequestChat2Direct) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_RequestChat2Direct)
}
func (x *RequestChat2Direct) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RequestChat2Direct) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RequestChat2Direct) New() CliMessage {
	return new(RequestChat2Direct)
}
func (*ResponseChatInfo) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_ResponseChatInfo)
}
func (x *ResponseChatInfo) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *ResponseChatInfo) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*ResponseChatInfo) New() CliMessage {
	return new(ResponseChatInfo)
}
