// Code generated by protoc-gen-chat. DO NOT EDIT.
// cli option
package message_cli

import (
	"google.golang.org/protobuf/proto"
)

func init() {
	AllMessage[uint32(CliCmd_CliCmd_ResponseCliSucces)] = new(ResponseCliSucces)
	AllMessage[uint32(CliCmd_CliCmd_ResponseCliFailure)] = new(ResponseCliFailure)
	AllMessage[uint32(CliCmd_CliCmd_RequestSignIn)] = new(RequestSignIn)
	InComingMessage[uint32(CliCmd_CliCmd_RequestSignIn)] = new(RequestSignIn)
}
func (*ResponseCliSucces) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_ResponseCliSucces)
}
func (x *ResponseCliSucces) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *ResponseCliSucces) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*ResponseCliSucces) New() CliMessage {
	return new(ResponseCliSucces)
}
func (*ResponseCliFailure) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_ResponseCliFailure)
}
func (x *ResponseCliFailure) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *ResponseCliFailure) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*ResponseCliFailure) New() CliMessage {
	return new(ResponseCliFailure)
}
func (*RequestSignIn) CmdId() uint32 {
	return uint32(CliCmd_CliCmd_RequestSignIn)
}
func (x *RequestSignIn) Marshal() ([]byte, error) {
	return proto.Marshal(x)
}
func (x *RequestSignIn) Unmarshal(in []byte) error {
	return proto.Unmarshal(in, x)
}
func (*RequestSignIn) New() CliMessage {
	return new(RequestSignIn)
}
