// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: cli/cli.proto

package message_cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CliCmd int32

const (
	CliCmd_CliCmd_None               CliCmd = 0
	CliCmd_CliCmd_ResponseCliSucces  CliCmd = 1
	CliCmd_CliCmd_ResponseCliFailure CliCmd = 2
	CliCmd_CliCmd_RequestSignIn      CliCmd = 3
)

// Enum value maps for CliCmd.
var (
	CliCmd_name = map[int32]string{
		0: "CliCmd_None",
		1: "CliCmd_ResponseCliSucces",
		2: "CliCmd_ResponseCliFailure",
		3: "CliCmd_RequestSignIn",
	}
	CliCmd_value = map[string]int32{
		"CliCmd_None":               0,
		"CliCmd_ResponseCliSucces":  1,
		"CliCmd_ResponseCliFailure": 2,
		"CliCmd_RequestSignIn":      3,
	}
)

func (x CliCmd) Enum() *CliCmd {
	p := new(CliCmd)
	*p = x
	return p
}

func (x CliCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CliCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_cli_cli_proto_enumTypes[0].Descriptor()
}

func (CliCmd) Type() protoreflect.EnumType {
	return &file_cli_cli_proto_enumTypes[0]
}

func (x CliCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CliCmd.Descriptor instead.
func (CliCmd) EnumDescriptor() ([]byte, []int) {
	return file_cli_cli_proto_rawDescGZIP(), []int{0}
}

type ResponseCliSucces struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InCmdId uint32 `protobuf:"varint,1,opt,name=inCmdId,proto3" json:"inCmdId,omitempty"`
}

func (x *ResponseCliSucces) Reset() {
	*x = ResponseCliSucces{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cli_cli_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCliSucces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCliSucces) ProtoMessage() {}

func (x *ResponseCliSucces) ProtoReflect() protoreflect.Message {
	mi := &file_cli_cli_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCliSucces.ProtoReflect.Descriptor instead.
func (*ResponseCliSucces) Descriptor() ([]byte, []int) {
	return file_cli_cli_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseCliSucces) GetInCmdId() uint32 {
	if x != nil {
		return x.InCmdId
	}
	return 0
}

type ResponseCliFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InCmdId     uint32 `protobuf:"varint,1,opt,name=inCmdId,proto3" json:"inCmdId,omitempty"`
	ErrorString string `protobuf:"bytes,2,opt,name=errorString,proto3" json:"errorString,omitempty"`
}

func (x *ResponseCliFailure) Reset() {
	*x = ResponseCliFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cli_cli_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCliFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCliFailure) ProtoMessage() {}

func (x *ResponseCliFailure) ProtoReflect() protoreflect.Message {
	mi := &file_cli_cli_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCliFailure.ProtoReflect.Descriptor instead.
func (*ResponseCliFailure) Descriptor() ([]byte, []int) {
	return file_cli_cli_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseCliFailure) GetInCmdId() uint32 {
	if x != nil {
		return x.InCmdId
	}
	return 0
}

func (x *ResponseCliFailure) GetErrorString() string {
	if x != nil {
		return x.ErrorString
	}
	return ""
}

type RequestSignIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RequestSignIn) Reset() {
	*x = RequestSignIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cli_cli_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSignIn) ProtoMessage() {}

func (x *RequestSignIn) ProtoReflect() protoreflect.Message {
	mi := &file_cli_cli_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSignIn.ProtoReflect.Descriptor instead.
func (*RequestSignIn) Descriptor() ([]byte, []int) {
	return file_cli_cli_proto_rawDescGZIP(), []int{2}
}

func (x *RequestSignIn) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RequestSignIn) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_cli_cli_proto protoreflect.FileDescriptor

var file_cli_cli_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x22, 0x2d, 0x0a, 0x11,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x12, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x37, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x70, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x43, 0x6d, 0x64,
	0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x43, 0x6d, 0x64, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x6c, 0x69, 0x43, 0x6d, 0x64, 0x5f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x10, 0x01, 0x12,
	0x1d, 0x0a, 0x19, 0x43, 0x6c, 0x69, 0x43, 0x6d, 0x64, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6c, 0x69, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x02, 0x12, 0x18,
	0x0a, 0x14, 0x43, 0x6c, 0x69, 0x43, 0x6d, 0x64, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x10, 0x03, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cli_cli_proto_rawDescOnce sync.Once
	file_cli_cli_proto_rawDescData = file_cli_cli_proto_rawDesc
)

func file_cli_cli_proto_rawDescGZIP() []byte {
	file_cli_cli_proto_rawDescOnce.Do(func() {
		file_cli_cli_proto_rawDescData = protoimpl.X.CompressGZIP(file_cli_cli_proto_rawDescData)
	})
	return file_cli_cli_proto_rawDescData
}

var file_cli_cli_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cli_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cli_cli_proto_goTypes = []interface{}{
	(CliCmd)(0),                // 0: message_cli.CliCmd
	(*ResponseCliSucces)(nil),  // 1: message_cli.ResponseCliSucces
	(*ResponseCliFailure)(nil), // 2: message_cli.ResponseCliFailure
	(*RequestSignIn)(nil),      // 3: message_cli.RequestSignIn
}
var file_cli_cli_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cli_cli_proto_init() }
func file_cli_cli_proto_init() {
	if File_cli_cli_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cli_cli_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCliSucces); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cli_cli_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCliFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cli_cli_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSignIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cli_cli_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cli_cli_proto_goTypes,
		DependencyIndexes: file_cli_cli_proto_depIdxs,
		EnumInfos:         file_cli_cli_proto_enumTypes,
		MessageInfos:      file_cli_cli_proto_msgTypes,
	}.Build()
	File_cli_cli_proto = out.File
	file_cli_cli_proto_rawDesc = nil
	file_cli_cli_proto_goTypes = nil
	file_cli_cli_proto_depIdxs = nil
}
