// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: message_obj/common.proto

package message_obj

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelMessageType int32

const (
	ChannelMessageType_ChannelMessageType_Drirect ChannelMessageType = 0
	ChannelMessageType_ChannelMessageType_Guild   ChannelMessageType = 1
	ChannelMessageType_ChannelMessageType_World   ChannelMessageType = 2
	ChannelMessageType_ChannelMessageType_Max     ChannelMessageType = 3
)

// Enum value maps for ChannelMessageType.
var (
	ChannelMessageType_name = map[int32]string{
		0: "ChannelMessageType_Drirect",
		1: "ChannelMessageType_Guild",
		2: "ChannelMessageType_World",
		3: "ChannelMessageType_Max",
	}
	ChannelMessageType_value = map[string]int32{
		"ChannelMessageType_Drirect": 0,
		"ChannelMessageType_Guild":   1,
		"ChannelMessageType_World":   2,
		"ChannelMessageType_Max":     3,
	}
)

func (x ChannelMessageType) Enum() *ChannelMessageType {
	p := new(ChannelMessageType)
	*p = x
	return p
}

func (x ChannelMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_obj_common_proto_enumTypes[0].Descriptor()
}

func (ChannelMessageType) Type() protoreflect.EnumType {
	return &file_message_obj_common_proto_enumTypes[0]
}

func (x ChannelMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelMessageType.Descriptor instead.
func (ChannelMessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_obj_common_proto_rawDescGZIP(), []int{0}
}

type GulidChatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid              uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Guild            uint64 `protobuf:"varint,2,opt,name=guild,proto3" json:"guild,omitempty"`
	CreatedTimestamp int64  `protobuf:"varint,3,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	Text             string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *GulidChatInfo) Reset() {
	*x = GulidChatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_obj_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GulidChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GulidChatInfo) ProtoMessage() {}

func (x *GulidChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_obj_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GulidChatInfo.ProtoReflect.Descriptor instead.
func (*GulidChatInfo) Descriptor() ([]byte, []int) {
	return file_message_obj_common_proto_rawDescGZIP(), []int{0}
}

func (x *GulidChatInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GulidChatInfo) GetGuild() uint64 {
	if x != nil {
		return x.Guild
	}
	return 0
}

func (x *GulidChatInfo) GetCreatedTimestamp() int64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *GulidChatInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type WorldChatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid              uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CreatedTimestamp int64  `protobuf:"varint,2,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	Text             string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *WorldChatInfo) Reset() {
	*x = WorldChatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_obj_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldChatInfo) ProtoMessage() {}

func (x *WorldChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_obj_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldChatInfo.ProtoReflect.Descriptor instead.
func (*WorldChatInfo) Descriptor() ([]byte, []int) {
	return file_message_obj_common_proto_rawDescGZIP(), []int{1}
}

func (x *WorldChatInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WorldChatInfo) GetCreatedTimestamp() int64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *WorldChatInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DirectChatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid              uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ReceiveId        uint64 `protobuf:"varint,2,opt,name=receiveId,proto3" json:"receiveId,omitempty"`
	CreatedTimestamp int64  `protobuf:"varint,3,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	Text             string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *DirectChatInfo) Reset() {
	*x = DirectChatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_obj_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectChatInfo) ProtoMessage() {}

func (x *DirectChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_obj_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectChatInfo.ProtoReflect.Descriptor instead.
func (*DirectChatInfo) Descriptor() ([]byte, []int) {
	return file_message_obj_common_proto_rawDescGZIP(), []int{2}
}

func (x *DirectChatInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DirectChatInfo) GetReceiveId() uint64 {
	if x != nil {
		return x.ReceiveId
	}
	return 0
}

func (x *DirectChatInfo) GetCreatedTimestamp() int64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *DirectChatInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ChannelMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ct        ChannelMessageType `protobuf:"varint,1,opt,name=ct,proto3,enum=message_obj.ChannelMessageType" json:"ct,omitempty"`
	ChannelId uint64             `protobuf:"varint,2,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Body      []byte             `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_obj_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_obj_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_message_obj_common_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelMessage) GetCt() ChannelMessageType {
	if x != nil {
		return x.Ct
	}
	return ChannelMessageType_ChannelMessageType_Drirect
}

func (x *ChannelMessage) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChannelMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_message_obj_common_proto protoreflect.FileDescriptor

var file_message_obj_common_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x22, 0x77, 0x0a, 0x0d, 0x47, 0x75, 0x6c, 0x69, 0x64,
	0x43, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x12, 0x2a, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x61, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x43, 0x68,
	0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x73, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x02, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6f,
	0x62, 0x6a, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x2a, 0x8c, 0x01, 0x0a, 0x12,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x72, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x10, 0x01,
	0x12, 0x1c, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x10, 0x02, 0x12, 0x1a,
	0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x03, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x73, 0x6e, 0x34, 0x6b, 0x65, 0x2f,
	0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_obj_common_proto_rawDescOnce sync.Once
	file_message_obj_common_proto_rawDescData = file_message_obj_common_proto_rawDesc
)

func file_message_obj_common_proto_rawDescGZIP() []byte {
	file_message_obj_common_proto_rawDescOnce.Do(func() {
		file_message_obj_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_obj_common_proto_rawDescData)
	})
	return file_message_obj_common_proto_rawDescData
}

var file_message_obj_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_obj_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_obj_common_proto_goTypes = []interface{}{
	(ChannelMessageType)(0), // 0: message_obj.ChannelMessageType
	(*GulidChatInfo)(nil),   // 1: message_obj.GulidChatInfo
	(*WorldChatInfo)(nil),   // 2: message_obj.WorldChatInfo
	(*DirectChatInfo)(nil),  // 3: message_obj.DirectChatInfo
	(*ChannelMessage)(nil),  // 4: message_obj.ChannelMessage
}
var file_message_obj_common_proto_depIdxs = []int32{
	0, // 0: message_obj.ChannelMessage.ct:type_name -> message_obj.ChannelMessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_obj_common_proto_init() }
func file_message_obj_common_proto_init() {
	if File_message_obj_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_obj_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GulidChatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_obj_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorldChatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_obj_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectChatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_obj_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_obj_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_obj_common_proto_goTypes,
		DependencyIndexes: file_message_obj_common_proto_depIdxs,
		EnumInfos:         file_message_obj_common_proto_enumTypes,
		MessageInfos:      file_message_obj_common_proto_msgTypes,
	}.Build()
	File_message_obj_common_proto = out.File
	file_message_obj_common_proto_rawDesc = nil
	file_message_obj_common_proto_goTypes = nil
	file_message_obj_common_proto_depIdxs = nil
}
